### ISSUE TITLE
Bug with compare.wvar

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/gmwm#138]
Hi guys,

I found a strange bug with the function compare.wvar. Here is an example:

```r
x1 = rnorm(100)
x2 = rnorm(100)
x3 = rnorm(100)

compare.wvar(wvar(x1), wvar(x2), wvar(x3), legend.label = c("Index","Coca Cola","GE"), split = F, auto.label.wvar = F)

```

@Wenchao-Yang: Any idea why is does this?

**Comment by coatless** [comment]
**Issue:**

![rplot](https://cloud.githubusercontent.com/assets/833642/13200293/3868a598-d807-11e5-90ae-9f333e6b3011.jpeg)

**Solution:**

Seems to be an issue with the use of: scale_size_manual and scale_shape_manual not aligning.

**Comment by coatless** [comment]
```r
library(gmwm)
x1 = rnorm(100)
x2 = rnorm(100)
x3 = rnorm(100)

compare.wvar(wvar(x1), wvar(x2), wvar(x3), legend.label = c("A","B","C"), split = F, auto.label.wvar = F)

compare.wvar(wvar(x1), wvar(x2), wvar(x3), legend.label = c("B","A","C"), split = F, auto.label.wvar = F)
```

Seems like it is because factors do not align for both of them. (e.g. during the cast, we lose the order of the factor.) 


![single_label](https://cloud.githubusercontent.com/assets/833642/13200559/2cf3f864-d813-11e5-9466-f3ccc5b52417.jpeg)

![split_labels](https://cloud.githubusercontent.com/assets/833642/13200560/2cf4c6c2-d813-11e5-9a96-6463717f5a04.jpeg)

**Comment by Wenchao-Yang** [comment]
Thanks! This is really helpful. I found the bugs and I will create a pull request.

**Comment by Wenchao-Yang** [comment]
This issue is fixed in the current pull request.
