### ISSUE TITLE
Extend WV Filters

### ISSUE THREAD

**Issue by coatless** [SMAC-Group/gmwm#140]
**Feature:**

It would be very nice to provide support for **MODWT** and **DWT** based decomposition using wavelet filters other than Haar. (We are still restricting the GMWM to using the Haar decomposition.) With this change, we can effectively compute the WV under these different filters as well.

Note: Robustness will only work with the **Haar filter**.

Per 9af93bd4bcce465e478227bb5702caf5cb232323, we now have a very dynamic way of calling WV filters. 

All that is needed is a translation of the filter coefficients into C++.

**Comment by robertomolinari** [comment]
Just to clear : we can’t use the GMWM with other filters until we have the corresponding theoretical form of WV (unless we use indirect inference). Otherwise, for simple WV computations I agree! Moreover, robustness works with other filters as well (we just require the relative wavelet coefficients to be stationary). If I misunderstood your email: sorry!!

**Comment by coatless** [comment]
There is no change to the GMWM procedure as we only have the Haar WV theoretical process forms loaded. 

The motivation behind the WV filter changes is to expand decomposition options given by `modwt()`, `dwt()`, and `wvar()` (e.g. simple WV computations). As a result, the feature puts the `gmwm` into more of a platform role for wavelet research since it has more flexibility in the aforementioned functions.

**Comment by robertomolinari** [comment]
Ok, that’s fine! The robust theory for the WV will hold also in this case.
