### ISSUE TITLE
Conversion AR(1) to GM

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/gmwm#97]

**Comment by coatless** [comment]
Did we want to set an explicit GM() term within the model? Or would it be sufficient to map it to AR(1)?

**Comment by janskaloud** [comment]
I suggest setting an explicit GM() term, although internally this just interprets AR(1) coefficient. Having GM() term will be practical for many engineers and avoids errors due to scale mis-interpretation.

On 22 Dec 2015, at 07:38, James J Balamuta <notifications@github.com<mailto:notifications@github.com>> wrote:


Did we want to set an explicit GM() term within the model? Or would it be sufficient to map it to AR(1)?

**Comment by stephaneguerrier** [comment]
Thanks Jan. I also think this is best approach. @coatless: the formula for converting AR1 to GM is straightforward but depends on the sampling frequency. Therefore, if a user wants to estimates a model with GM processes but has not set-up a frequency for his data I think a warning should be returned as I am guessing our default frequency is 1, correct?

**Comment by coatless** [comment]
Default frequency is indeed 1. The warning is definitely possible.

AR1 to GM has the following parameter transforms if I recall:

phi = exp(-beta * delta_t)
sigma^2 = sigma^2_gm*(1-exp(-2*beta*delta_t))

So:

beta = -ln(phi)/delta_t

sigma^2_gm = sigma^2 + exp(-2*beta*delta_t)
..
sigma^2_gm = sigma^2 + phi^2

Implementing this outside of the estimation procedure is trivial. Within the procedure itself, it may be a little bit problematic due to the queuing system currently in place not really having support for freq (outside of tossing it in obj.desc). 

Regardless, if the above is accurate, then this term should be available sometime tomorrow.

**Comment by stephaneguerrier** [comment]
Hi James, an implementation outside of the estimation procedure is fine. Thanks!

**Comment by coatless** [comment]
See ?GM()

Requires use of gts, imu, or newly added `freq=` for `gmwm` with `matrix`,`ts`, or `data.frame`
